### ISSUE TITLE
[1.12.2] Compressed Block Recipes Can't be removed with CraftTweaker.

### ISSUE THREAD

**Issue by ToMe25** [Mrbysco/Sky_Compression#7] opened 2018-11-09 13:50 UTC
I was Trying to remove the Recipe for Compressed Stone with CraftTweaker and figured out: it doesn't works.

Used Mods:
CodeChickenLib-1.12.2-3.2.2.353-universal,
ChickenASM-1.12-1.0.2.7,
CraftTweaker2-1.12-4.1.11,
skyresources-2.3.8
and Sky+Compression-1.2.2.1

This was my CraftTweaker Script:
`recipes.remove(<sc:compressedstone>);`,

my CraftTweaker.log: 
```
[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: CompressedStone.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 2ms
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [recipeevent | crafttweaker]]
[INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: CompressedStone.zs}
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 315ms
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook
```

and my [latest.log](https://github.com/Mrbysco/Sky_Compression/files/2566063/latest.log).

**Comment by MaxNeedsSnacks** [comment] 2019-03-04 21:50
Hey there,

I'm not exactly experienced at writing MC mods (yet), but I think I found out what the issue is that causes this problem: When you're registering your crafting / processing recipes in post init, CraftTweaker has already finished doing its job entirely, meaning it's simply impossible to remove any recipes as none of them have been loaded when CT goes through the script.

Now, I'm not entirely sure whether there's a valid reason for you to call the crafting helper in postinit and not in an earlier phase (or, like recommended by forge, as part of the registry events after preinit), but if there is, please do feel free to correct me.

Otherwise, an easy fix for this issue would be to move the according method call(s) into an earlier phase, if possible, so that crafttweaker actually has recipes to remove when it loads.

If it's not possible, then a config flag to enable / disable certain recipes would probably be a nice idea, but that's only relevant if there's no other way around it.

**Comment by ToMe25** [comment] 2019-03-05 10:56
Just found that with the OreDictionary now, but he should register the Items to OreDictionary directly after registering the Items.
That means on the RegistryEvent.Register or on preInit.

You are right, he could move the Recipe Registration to the Event for that or Init, but he should if possible convert the Recipe to Recipe JSON Files.

**Comment by MaxNeedsSnacks** [comment] 2019-03-05 11:17
I may actually do some proper work on my fork rather than just hotfixing a minor issue like this, but this sounds like a lot of stuff I'd need to do to fix one minor issue :P

**Comment by ToMe25** [comment] 2019-03-05 11:33
You don't need to change the Recipes to JSON Files.
It also works like this, but JSON Files are the recommended way to add Recipes.
Also i am not sure what Recipes he adds, if he adds very dynamic Recipes he does it right.
The only way i know about how to add dynamic Recipes is still in the Code not as JSON.

**Comment by MaxNeedsSnacks** [comment] 2019-03-05 11:45
True, but then again...

*i kind of want to :P*

**Comment by jelaw21** [comment] 2019-05-02 23:44
I too am having crafttweaker issues. I tried to remove all the rock grinding recipes so I can give them my own drop rates, but now matter what I did, the recipes still existed.

**Comment by ToMe25** [comment] 2019-05-03 14:46
@MaxNeedsSnacks any updates about this?

**Comment by Mrbysco** [comment] 2019-05-03 15:17
Finally found some time. Will see what I can do about this

**Comment by ToMe25** [comment] 2019-05-03 15:34
It should be enough to register the Recipes earlyer but you could also covert them the Recipe JSON's.

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 16:05
@ToMe25 I had a fork of SkyCompression ready but decided to call it quits since it was

a) such a small change
b) my new semester was just starting
c) my overly ambitious ass would've probably made way too many "optimisations" that would only end up hurting code quality in the end lol

But yeah, nice to see Bysco is back in business!

**Comment by Mrbysco** [comment] 2019-05-03 16:11
I've been working on so many mods that I lost track of open issues. Github should have a page where you can see all open issues on all repos.

**Comment by ToMe25** [comment] 2019-05-03 16:19
Yeah i miss a feature like that Too.

And thanks for your comment Max.

**Comment by Mrbysco** [comment] 2019-05-03 16:21
As you can see in my latest commit I'm refactoring a bit. Like adhering to package naming convention. (Aka lowercase only as uppercase can cause issues)

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 16:46
@Mrbysco I found that the best way to keep track of all issues you wanna work on is have a bot assign them to you on creation or sth similar, at least for some repos that's a nice idea ^^

**Comment by Mrbysco** [comment] 2019-05-03 16:46
I have around 30 repos... :P

**Comment by Mrbysco** [comment] 2019-05-03 16:46
So what have you done in your fork? as you've never pushed your changes.

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 16:46
But yeah I definitely agree that that's a feature that's lacking from GitHub, just a "Issues from repos you're collaborating on" button or sth similar would be nice

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 16:48
Mostly refactoring, I tried doing stuff to the textures such that it'd be easier to add new compressed blocks in the future (working with overlays and such), but I'm really just... bad at texture-related stuff lol
I also moved the compressed block and item recipes to JSON files though ^^

**Comment by Mrbysco** [comment] 2019-05-03 16:50
I took over the mod and tried to keep it as close to how it was.

**Comment by Mrbysco** [comment] 2019-05-03 16:55
If you want could you publish the jsons for the recipes? That way I don't have to do what someone already done?

**Comment by ToMe25** [comment] 2019-05-03 17:03
Please move the Machine Recipe Registration to preInit/Init.

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 17:22
Oh, to be 100% honest I wiped my hard drive in early April so idk whether it's still on there but I can honestly just... make the files again I mean they *were* pretty much just copy and pasting the same base with some minor refactoring each time

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 17:51
Also something I just noticed while remaking those files, you changed package names and such to "skycompression" instead of sc everywhere, EXCEPT for the Reference class, meaning that every block / item will still have the sc mod id

**Comment by ToMe25** [comment] 2019-05-03 17:53
But if he would change the Item Modid that would remove all Items from existing worlds.
So i guess it is better to let it be sc.
Or he would need to use a DataFixer.

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 17:56
Yeah, I just realised, that would be... suboptimal

**Comment by Mrbysco** [comment] 2019-05-03 18:01
Package name was hqbanana.SkyCompression. I just changed it to hqbanana.skycompression.

**Comment by Mrbysco** [comment] 2019-05-03 18:02
There's no need for it to be the same as the MODID :P

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 18:02
Ah, yeah ik it just seemed like "best practice" to me lol

**Comment by Mrbysco** [comment] 2019-05-03 18:49
Made the jsons already :3 I had a tool to convert code based to json.

**Comment by Mrbysco** [comment] 2019-05-03 18:50
Even have a condition to check if justanothersnad is installed. As there's some recipes counting on that to be installed.

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 18:52
Awww I was *just* looking for a tool for that and couldn't find one.

Weeeeeell, at least I just trained my ten finger typing at least :P

**Comment by Mrbysco** [comment] 2019-05-03 19:05
Max for the future it's good to bookmark https://gist.github.com/williewillus/a1a899ce5b0f0ba099078d46ae3dae6e (It's by WillieWillus)

**Comment by ToMe25** [comment] 2019-05-03 19:13
Thank you for the Like :)

**Comment by Mrbysco** [comment] 2019-05-03 19:17
Max as you can see in my latest commit I've relocated the initilization of the recipes to preInit and added alllll the json recipes.

**Comment by Mrbysco** [comment] 2019-05-03 19:17
They seem to work from my testing.

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 19:33
Looks good to me, and thanks for the script link, that might be VERY valuable to me and others in the future ^^

**Comment by Mrbysco** [comment] 2019-05-03 19:34
After 8 months I can finally close this issue as I upload a new release to Curse

**Comment by MaxNeedsSnacks** [comment] 2019-05-03 19:36
One more very minor thing that doesn’t really justify making another issue so I’ll just put it here - I feel like some more oredict names would be nice to have, for example compressed1xStone on the compressed stone and so on, might help with certain oredicted recipes

**Comment by Mrbysco** [comment] 2019-05-03 19:37
Was planning on doing so either way :P

**Comment by Mrbysco** [comment] 2019-05-03 19:40
New version has been uploaded to curse

**Comment by Mrbysco** [comment] 2019-05-03 19:41
As you might have seen. I also changed the file naming, replaced the space with a -.

**Comment by Mrbysco** [comment] 2019-05-03 19:41
https://minecraft.curseforge.com/projects/sky-compression/files/2706816

**Closed by Mrbysco** 2019-05-03 19:41 UTC
Labels: Fixed next release, bug
